pub const ENCRYPTION_CONNECT_KEY: &str = "ENCRYPTION_CONNECT_KEY";
pub const ENCRYPTION_KEY_DEVICE_ID: &str = "ENCRYPTION_KEY_DEVICE_ID";
pub const ENCRYPTION_KEY_PRICE: &str = "ENCRYPTION_KEY_PRICE";
pub const CONNECT_MSG: &str = "CONNECT_MSG";
pub const XMINISTER_API_KEY: &str = "XMINISTER_API_KEY";