pub const ENCRYPTION_CONNECT_KEY: &str = "ENCRYPTION_CONNECT_KEY";
pub const ENCRYPTION_DEVICE_ID_KEY: &str = "ENCRYPTION_DEVICE_ID_KEY";
pub const ENCRYPTION_KEY_PRICE: &str = "ENCRYPTION_KEY_PRICE";
pub const CONNECT_MSG: &str = "CONNECT_MSG";
pub const XMINISTER_API_KEY: &str = "XMINISTER_API_KEY";
pub const XMINISTER_METAL_API_KEY: &str = "XMINISTER_METAL_API_KEY";
pub const DATABASE_URL: &str = "DATABASE_URL";
pub const SESSION_KEY: &str = "SESSION_KEY";